---
name: Notify Packagist

on:
  push:
    branches: [ "main","develop","tests" ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify Packagist
        uses: mnavarrocarter/packagist-update@v1.0.0
        with:
          username: ${{ secrets.PACKAGIST_USERNAME }}
          api_token: ${{ secrets.PACKAGIST_TOKEN }}
