---
name: PHP Composer

on:
  push:
    branches: [ "main","develop","tests" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Composer manifest
        run: composer validate --strict

      - name: Cache Composer dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json','**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: make install

      - name: Lint PHP code (PSR-12)
        run: make test-phplint

      - name: Run PHPUnit tests
        run: make test-phpunit

      - name: Run PHPStan tests
        run: make test-phpstan

      - name: Upload PHPUnit report
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-report
          path: .phpunit.junit.xml
          include-hidden-files: true
